import type { Location } from "../types";

export const TECH_PARKS: Location[] = [
	{
		name: "Manyata Tech Park",
		lat: 13.0451,
		lng: 77.6206,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Embassy GolfLinks (EGL)",
		lat: 12.9461,
		lng: 77.6475,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Bagmane Solarium City",
		lat: 12.9818,
		lng: 77.6946,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Bagmane Constellation Business Park",
		lat: 12.9129,
		lng: 77.6835,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "EcoWorld",
		lat: 12.912,
		lng: 77.6749,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "EcoSpace Business Park",
		lat: 12.9237,
		lng: 77.6781,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Cessna Business Park",
		lat: 12.9351,
		lng: 77.6936,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "ITPL (International Tech Park Bangalore)",
		lat: 12.9876,
		lng: 77.7377,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Global Village Tech Park",
		lat: 12.915,
		lng: 77.518,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Electronics City Phase 1",
		lat: 12.8532,
		lng: 77.6657,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Electronics City Phase 2",
		lat: 12.8398,
		lng: 77.6781,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Brigade Tech Gardens",
		lat: 12.96,
		lng: 77.7126,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Prestige Tech Park",
		lat: 12.9367,
		lng: 77.6917,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "RMZ Infinity",
		lat: 12.9912,
		lng: 77.659,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Embassy Tech Village (ETV), Bellandur",
		lat: 12.9248,
		lng: 77.6826,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "IBC Knowledge Park, Bannerghatta Road",
		lat: 12.936,
		lng: 77.5996,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "DivyaSree Technopolis, Yemlur",
		lat: 12.9431,
		lng: 77.6811,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Kalyani Tech Park, Brookefield",
		lat: 12.9723,
		lng: 77.7145,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Global Technology Park, Bellandur",
		lat: 12.9238,
		lng: 77.6828,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "RGA Tech Park, Sarjapur Road",
		lat: 12.9038,
		lng: 77.6976,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "RMZ Millenia, Ulsoor",
		lat: 12.9734,
		lng: 77.6192,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "SJR I-Park, Whitefield",
		lat: 12.984,
		lng: 77.7345,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Gold Hill Square, Hosur Road",
		lat: 12.8953,
		lng: 77.6366,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Gopalan Signature Tower, Old Madras Road",
		lat: 12.9922,
		lng: 77.6612,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "DivyaSree Greens, Domlur (near EGL)",
		lat: 12.953,
		lng: 77.6415,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Sigma Soft Tech Park, Whitefield",
		lat: 12.9667,
		lng: 77.7471,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "AMR Tech Park, Hosur Road",
		lat: 12.905,
		lng: 77.632,
		city: "Bengaluru",
		category: "office",
	},
	{
		name: "Helios Business Park, Kadubeesanahalli",
		lat: 12.935,
		lng: 77.694,
		city: "Bengaluru",
		category: "office",
	},

	// Popular Bengaluru Residential
	{
		name: "Prestige Shantiniketan, Whitefield",
		lat: 12.9941,
		lng: 77.7288,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Sobha Dream Acres, Panathur",
		lat: 12.935,
		lng: 77.712,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Brigade Gateway, Rajajinagar",
		lat: 13.0122,
		lng: 77.5567,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "HSR Layout, Bengaluru",
		lat: 12.9121,
		lng: 77.6446,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Indiranagar, Bengaluru",
		lat: 12.9784,
		lng: 77.6408,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Koramangala, Bengaluru",
		lat: 12.9352,
		lng: 77.6245,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Godrej Eternity, Kanakapura Road",
		lat: 12.86,
		lng: 77.53,
		city: "Bengaluru",
		category: "residential",
	},
	{
		name: "Phoenix One Bangalore West, Rajajinagar",
		lat: 13.0,
		lng: 77.55,
		city: "Bengaluru",
		category: "residential",
	},

	// Pune IBM Offices
	{
		name: "IBM Embassy Techzone (ETZ), Hinjewadi",
		lat: 18.5913,
		lng: 73.7191,
		city: "Pune",
		category: "office",
	},
	{
		name: "IBM Panchshil Tech Park, Yerwada",
		lat: 18.5516,
		lng: 73.8935,
		city: "Pune",
		category: "office",
	},
	{
		name: "IBM SP Infocity, Hadapsar",
		lat: 18.47,
		lng: 73.96,
		city: "Pune",
		category: "office",
	},

	// Popular Pune Residential
	{
		name: "Magarpatta City, Hadapsar",
		lat: 18.5159,
		lng: 73.9263,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Amanora Park Town, Hadapsar",
		lat: 18.5204,
		lng: 73.9399,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Kolte Patil Life Republic, Hinjawadi",
		lat: 18.61,
		lng: 73.74,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Baner, Pune",
		lat: 18.559,
		lng: 73.7797,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Kothrud, Pune",
		lat: 18.5074,
		lng: 73.8077,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Wakad, Pune",
		lat: 18.598,
		lng: 73.765,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Viman Nagar, Pune",
		lat: 18.5679,
		lng: 73.9143,
		city: "Pune",
		category: "residential",
	},
	{
		name: "Kalyani Nagar, Pune",
		lat: 18.5463,
		lng: 73.9033,
		city: "Pune",
		category: "residential",
	},
];
